services:
  app:
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    build: .
    restart: always
    volumes:
      - ./:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
      - app_data:/data
      - app_config:/config
    # command: ["php", "artisan", "octane:start", "--watch"]
    environment:
      CHOKIDAR_USEPOLLING: "true"
    tty: true
  mailpit:
    image: axllent/mailpit
    restart: always
    volumes:
      - ./mailpi_data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
volumes:
  app_data:
  app_config:
