services:
  #################################################
  # DB (MySQL)
  #################################################
  db:
    image: "mysql:8.0"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 20s
  ##################################################
  # REDIS
  ##################################################
  redis:
    image: "redis:7.4"
    restart: always
    volumes:
      - "redis-data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 20s
    depends_on:
      db:
        condition: service_healthy
        restart: true
  ##################################################
  # PHPMYADMIN
  ##################################################
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
        restart: true
  #################################################
  # OCTANE:FRANKENPHP
  #################################################
  app:
    build:
      target: common
    restart: always
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD", "php", "artisan", "octane:status"]
      start_period: 20s
    command: >
      sh -c "
        php artisan migrate --isolated --force &&
        php artisan octane:frankenphp --host=0.0.0.0
      "
    depends_on:
      redis:
        condition: service_healthy
        restart: true
  #################################################
  # SSR
  #################################################
  ssr:
    build:
      target: common
    restart: always
    volumes:
      - ssr_data:/data
      - ssr_config:/config
    command: ["php", "artisan", "inertia:start-ssr"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13714/render"]
      start_period: 20s
    expose:
      - "13714"
    depends_on:
      app:
        condition: service_healthy
        restart: true
  #################################################
  # CRON
  #################################################
  cron:
    build:
      target: common
    restart: always
    volumes:
      - cron_data:/data
      - cron_config:/config
    command: ["cron", "-f"]
    healthcheck:
      test: ["CMD", "pgrep", "-f", "cron"]
      start_period: 20s
    depends_on:
      app:
        condition: service_healthy
        restart: true
  ##################################################
  # PROXY
  ##################################################
  proxy:
    build:
      target: caddy-reverse-proxy
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - proxy_data:/data
      - proxy_config:/config
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      PMA_APP_DOMAIN: ${PMA_APP_DOMAIN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2019/metrics"]
      start_period: 20s
    depends_on:
      ssr:
        condition: service_healthy
        restart: true
  ##################################################
  # VOLUMES
  ##################################################
volumes:
  caddy_data:
  caddy_config:
  ##################################################
  proxy_data:
  proxy_config:
  ##################################################
  horizon_data:
  horizon_config:
  ##################################################
  mysql-data:
  redis-data:
  ##################################################
  cron_data:
  cron_config:
  ##################################################
  ssr_data:
  ssr_config:
