services:
  #################################################
  # OCTANE:FRANKENPHP
  #################################################
  app:
    image: ghcr.io/y-l-g/test-inertia2.0:main
    restart: always
    volumes:
      - laravel_app_caddy_data:/data
      - laravel_app_caddy_config:/config
    healthcheck:
      test: ["CMD", "php", "artisan", "octane:status"]
      start_period: 20s
    command: sh -c 'php artisan octane:frankenphp --host=0.0.0.0'
    environment:
      - APP_NAME=laravel_app
    secrets:
      - laravel_app_DB_PASSWORD
      - laravel_app_REDIS_PASSWORD
      - laravel_app_APP_URL
      - laravel_app_APP_KEY
    entrypoint: start-container
    networks:
      - laravel_app
  #################################################
  # SSR
  #################################################
  ssr:
    image: ghcr.io/y-l-g/test-inertia2.0:main
    restart: always
    volumes:
      - laravel_app_ssr_data:/data
      - laravel_app_ssr_config:/config
    command: ["php", "artisan", "inertia:start-ssr"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13714/render"]
      start_period: 20s
    environment:
      - APP_NAME=laravel_app
    secrets:
      - laravel_app_DB_PASSWORD
      - laravel_app_REDIS_PASSWORD
      - laravel_app_APP_URL
      - laravel_app_APP_KEY
    networks:
      - laravel_app
  #################################################
  # CRON
  #################################################
  cron:
    image: ghcr.io/y-l-g/test-inertia2.0:main
    restart: always
    volumes:
      - laravel_app_cron_data:/data
      - laravel_app_cron_config:/config
    command: ["cron", "-f"]
    healthcheck:
      test: ["CMD", "pgrep", "-f", "cron"]
      start_period: 20s
    environment:
      - APP_NAME=laravel_app
    secrets:
      - laravel_app_DB_PASSWORD
      - laravel_app_REDIS_PASSWORD
      - laravel_app_APP_URL
      - laravel_app_APP_KEY
    entrypoint: start-container
    networks:
      - laravel_app
  ##################################################
  # VOLUMES
  ##################################################
volumes:
  laravel_app_caddy_data:
  laravel_app_caddy_config:
  ##################################################
  laravel_app_cron_data:
  laravel_app_cron_config:
  ##################################################
  laravel_app_ssr_data:
  laravel_app_ssr_config:
secrets:
  laravel_app_DB_PASSWORD:
    external: true
  laravel_app_REDIS_PASSWORD:
    external: true
  laravel_app_APP_URL:
    external: true
  laravel_app_APP_KEY:
    external: true
networks:
  laravel_app:
    external: true
