name: Deploy
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        env:
          DOT_ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            if [ ! -d "test.yleg.ovh" ]; then
              git clone git@github.com:y-l-g/test-inertia2.0.git test.yleg.ovh || exit 1
            fi
            cd test.yleg.ovh || exit 1
            git checkout main || exit 1
            git pull || exit 1
             echo "$DOT_ENV" > .env || exit 1
            docker compose down || exit 1

            docker compose up -d db || exit 1
            echo "Attente du démarrage de la base de données..."
            sleep 30

            # Vérifier l'état de la base de données
            if ! docker compose ps | grep db | grep -q "healthy"; then
              echo "La base de données n'a pas démarré correctement"
              docker compose logs db
              exit 1
            fi

            docker compose up -d --wait --build || exit 1
            echo "Attente du démarrage complet des services..."
            sleep 20

            rm .env || exit 1
